### ISSUE TITLE
Support Syndication Links and Post Kinds

### ISSUE THREAD

**Issue by dshanske** [pfefferle/SemPress#48]
Both Syndication Links and Post Kinds add their markup to inside the_content block, by necessity. Asking for SemPress to support an alternative position. We discussed a possible hook some time ago.

**Comment by bekopharm** [comment]
I fiddled with this today based on the solution in [Autonomie](https://github.com/pfefferle/Autonomie/). It's just a hack for now but I may improve this to a solution for #48.

The troublesome part is that it does affect CSS as well even when the Syndication Links / Post Kinds CSS is not removed so this may break existing layouts. So I'm uncertain about making a PR of this or go with a child theme since I'm using a lot of CSS tweaks on my SemPress installation by now anyway.

**Comment by pfefferle** [comment]
I would love to see a PR!
