### ISSUE TITLE
Syndicatiion Views

### ISSUE THREAD

**Issue by jgmac1106** [pfefferle/SemPress#62]
When syndicating to Twitter you only get the post # and the url as it looks like p-name gets assigned to the url, and the content doesn't display in a Tweet.

**Comment by Zegnat** [comment]
Pre-face: apart from Bridgy (and possible other third-party syndication services) this has nothing to do with syndication.

Here is a test note by @jgmac1106: [“test note.”](https://sempress.jgregorymcverry.com/uncategorized/77/)

While it was expected that this would be a note post – and thus be title-less – the theme still renders a title above it based on the post ID (“#77”). This title also get the microformats title classes applied (both mf1 `entry-title` and mf2 `p-name`). Consumers following [Post Type Discovery](https://www.w3.org/TR/post-type-discovery/) will thus see it as a titled article rather than a note.

The specific consumer that often gives people unexpected results is [Bridgy](https://brid.gy/). For notes people expect the content and permalink to get tweeted out, and for articles the title and permalink. Because the theme currently turns every note into an article tweets will simply contain the post ID and permalink, e.g.:

> #77: https://sempress.jgregorymcverry.com/uncategorized/77/

I think SemPress should either remove the `h1` post title completely when there is no title, or if the presentation shouldn’t be changed at least drop the microformats in the case of untitled notes.
